package com.afterlife.systempendataanwarga.enums;

public enum Pekerjaan { 
    
    BELUM_BEKERJA_TIDAK_BEKERJA("Belum Bekerja / Tidak Bekerja"),
    PELAJAR_MAHASISWA("Pelajar / Mahasiswa"),
    PENSIUNAN("Pensiunan"),
    PEGAWAI_NEGERI_SIPIL("Pegawai Negeri Sipil"),
    TENTARA_NASIONAL_INDONESIA("Tentara Nasional Indonesia"),
    KEPOLISIAN_RI("Kepolisian RI"),
    PERDAGANGAN("Perdagangan"),
    PETANI_PEKEBUN("Petani / Pekebun"),
    PETERNAK("Peternak"),
    NELAYAN_PERIKANAN("Nelayan / Perikanan"),
    INDUSTRI("Industri"),
    KONSTRUKSI("Konstruksi"),
    TRANSPORTASI("Transportasi"),
    KARYAWAN_SWASTA("Karyawan Swasta"),
    KARYAWAN_BUMN("Karyawan BUMN"),
    KARYAWAN_BUMD("Karyawan BUMD"),
    KARYAWAN_HONORER("Karyawan Honorer"),
    BURUH_HARIAN_LEPAS("Buruh Harian Lepas"),
    BURUH_TANI_PERKEBUNAN("Buruh Tani / Perkebunan"),
    BURUH_NELAYAN_PERIKANAN("Buruh Nelayan / Perikanan"),
    BURUH_PETERNAK("Buruh Peternakan"),
    PEMBANTU_RUMAH_TANGGA("Pembantu Rumah Tangga"),
    TUKANG_CUKUR("Tukang Cukur"),
    TUKANG_LISTRIK("Tukang Listrik"),
    TUKANG_BATU("Tukang Batu"),
    TUKANG_KAYU("Tukang Kayu"),
    TUKANG_SOL_SEPATU("Tukang Sol Sepatu"),
    TUKANG_LAS_PANDAI_BESI("Tukang Las / Pandai Besi"),
    TUKANG_JAHIT("Tukang Jahit"),
    TUKANG_GIGI("Tukang Gigi"),
    PENATA_RIAS("Penata Rias"),
    PENATA_BUSANA("Penata Busana"),
    PENATA_RAMBUT("Penata Rambut"),
    MEKANIK("Mekanik"),
    SENIMAN("Seniman"),
    TABIB("Tabib"),
    PARAJI("Paraji"),
    PERANCANG_BUSANA("Perancang Busana"),
    PENTERJEMAH("Penterjemah"),
    IMAM_MASJID("Imam Masjid"),
    PENDETA("Pendeta"),
    PASTOR("Pastor"),
    WARTAWAN("Wartawan"),
    USTADZ_MUBALIGH("Ustadz / Mubaligh"),
    JURU_MASAK("Juru Masak"),
    PROMOTOR_ACARA("Promotor Acara"),
    ANGGOTA_DPR_RI("Anggota DPR-RI"),
    ANGGOTA_DPD("Anggota DPD"),
    ANGGOTA_BPK("Anggota BPK"),
    PRESIDEN("Presiden"),
    WAKIL_PRESIDEN("Wakil Presiden"),
    ANGGOTA_MAHKAMAH_KONSTITUSI("Anggota Mahkamah Konstitusi"),
    ANGGOTA_KABINET_KEMENTERIAN("Anggota Kabinet / Kementerian"),
    DUTA_BESAR("Duta Besar"),
    GUBERNUR("Gubernur"),
    WAKIL_GUBERNUR("Wakil Gubernur"),
    BUPATI("Bupati"),
    WAKIL_BUPATI("Wakil Bupati"),
    WALIKOTA("Walikota"),
    WAKIL_WALIKOTA("Wakil Walikota"),
    ANGGOTA_DPRD_PROVINSI("Anggota DPRD Provinsi"),
    ANGGOTA_DPRD_KABUPATEN_KOTA("Anggota DPRD Kabupaten / Kota"),
    DOSEN("Dosen"),
    GURU("Guru"),
    PILOT("Pilot"),
    PENGACARA("Pengacara"),
    NOTARIS("Notaris"),
    ARSITEK("Arsitek"),
    AKUNTAN("Akuntan"),
    KONSULTAN("Konsultan"),
    DOKTER("Dokter"),
    BIDAN("Bidan"),
    PERAWAT("Perawat"),
    APOTEKER("Apoteker"),
    PSIKIATER_PSIKOLOG("Psikiater / Psikolog"),
    PENYIAR_TELEVISI("Penyiar Televisi"),
    PENYIAR_RADIO("Penyiar Radio"),
    PELAUT("Pelaut"),
    PENELITI("Peneliti"),
    SOPIR("Sopir"),
    PIALANG("Pialang"),
    PARANORMAL("Paranormal"),
    PEDAGANG("Pedagang"),
    PERANGKAT_DESA("Perangkat Desa"),
    KEPALA_DESA("Kepala Desa"),
    BIARAWATI("Biarawati"),
    WIRASWASTA("Wiraswasta");



    private  String labelPekerjaan;
    
    private Pekerjaan(String labelPekerjaan) {
        this.labelPekerjaan = labelPekerjaan;
    }
    
    public String getDisplaylabelPekerjaan() {
        return labelPekerjaan;
    }

}
