package com.afterlife.aplikasikatar.enums;

public enum Kota {
    AMBON("Ambon"),
    BANDA_ACEH("Banda Aceh"),
    BANDAR_LAMPUNG("Bandar Lampung"),
    BANDUNG("Bandung"),
    BANJARBARU("Banjarbaru"),
    BANJARMASIN("Banjarmasin"),
    BANYUWANGI("Banyuwangi"),
    BENGKULU("Bengkulu"),
    BENGKULU_SELATAN("Bengkulu Selatan"),
    BENGKULU_TENGAH("Bengkulu Tengah"),
    BENGKULU_UTARA("Bengkulu Utara"),
    BIMA("Bima"),
    BINJAI("Binjai"),
    BLITAR("Blitar"),
    BONTANG("Bontang"),
    BUKIT_TINGGI("Bukit Tinggi"),
    BALIKPAPAN("Balikpapan"),
    BATAM("Batam"),
    BAU_BAU("Bau-Bau"),
    BEKASI("Bekasi"),
    BINTUHAN("Bintuhan"),
    BIREUEN("Bireuen"),
    BITUNG("Bitung"),
    BLORA("Blora"),
    BOGOR("Bogor"),
    BONDOWOSO("Bondowoso"),
    BONE("Bone"),
    BOYOLALI("Boyolali"),
    BREBES("Brebes"),
    BULUKUMBA("Bulukumba"),
    BULUNGAN("Bulungan"),
    BUNGKULU("Bungkulu"),
    BUOL("Buol"),
    BURU("Buru"),
    BUTON("Buton"),
    CIBINONG("Cibinong"),
    CILEGON("Cilegon"),
    CIREBON("Cirebon"),
    DEMAK("Demak"),
    DENPASAR("Denpasar"),
    DEPOK("Depok"),
    DUMAI("Dumai"),
    ENDE("Ende"),
    ENREKANG("Enrekang"),
    FLORES("Flores"),
    GIANJAR("Gianjar"),
    GORONTALO("Gorontalo"),
    GOWA("Gowa"),
    GRESIK("Gresik"),
    GROBOGAN("Groboan"),
    INDRAMAYU("Indramayu"),
    JAKARTA("Jakarta"),
    JAMBI("Jambi"),
    JAYAPURA("Jayapura"),
    JEMBER("Jember"),
    JENEPONTO("Jeneponto"),
    JEPARA("Jepara"),
    JOMBANG("Jombang"),
    KALABAKAN("Kalabakan"),
    KALBAR("Kalbar"),
    KALIMANTAN("Kalimantan"),
    KARANGANYAR("Karanganyar"),
    KARAWANG("Karawang"),
    KEBUMEN("Kebumen"),
    KEDIRI("Kediri"),
    KENDAL("Kendal"),
    KENDARI("Kendari"),
    KEPULAUAN("Kepulauan"),
    KETAPANG("Ketapang"),
    KLATEN("Klaten"),
    KOLAKA("Kolaka"),
    KOTABARU("Kotabaru"),
    KOTAWARINGIN("Kotawaringin"),
    KUBU_RAYA("Kubu Raya"),
    KUDUS("Kudus"),
    KULONPROGO("Kulonprogo"),
    KUNINGAN("Kuningan"),
    KUPANG("Kupang"),
    LAMPUNG("Lampung"),
    LOMBOK("Lombok"),
    LUWU("Luwu"),
    MADURA("Madura"),
    MAGELANG("Magelang"),
    MAJALENGKA("Majalengka"),
    MAKASSAR("Makassar"),
    MALANG("Malang"),
    MANADO("Manado"),
    MANOKWARI("Manokwari"),
    MARTAPURA("Martapura"),
    MASOHI("Masohi"),
    MATARAM("Mataram"),
    MEDAN("Medan"),
    MELAWI("Melawi"),
    METRO("Metro"),
    MIMIKA("Mimika"),
    MOJOKERTO("Mojokerto"),
    MUNA("Muna"),
    MUNTOK("Muntok"),
    NABIRE("Nabire"),
    NUNUKAN("Nunukan"),
    PACITAN("Pacitan"),
    PADANG("Padang"),
    PADANG_PANJANG("Padang Panjang"),
    PADANG_SIDEMPUAN("Padang Sidempuan"),
    PAGAR_ALAM("Pagar Alam"),
    PALANGKARAYA("Palangkaraya"),
    PALEMBANG("Palembang"),
    PALOPO("Palopo"),
    PALU("Palu"),
    PAMEKASAN("Pamekasan"),
    PANDAAN("Pandaan"),
    PANGKALAN_BUN("Pangkalan Bun"),
    PANGKAL_PINANG("Pangkal Pinang"),
    PARE_PARE("Parepare"),
    PARIAMAN("Pariaman"),
    PASURUAN("Pasuruan"),
    PATI("Pati"),
    PAYAKUMBUH("Payakumbuh"),
    PEKALONGAN("Pekalongan"),
    PEKANBARU("Pekanbaru"),
    PELAIHARI("Pelaihari"),
    PEMATANG_SIANTAR("Pematang Siantar"),
    PENDOPO("Pendopo"),
    PENGGARANGAN("Penggarangan"),
    PENGOEH("Pengoe"),
    PESISIR_SELATAN("Pesisir Selatan"),
    PINRANG("Pinrang"),
    PONTIANAK("Pontianak"),
    POSO("Poso"),
    PRABUMULIH("Prabumulih"),
    PROBOLINGGO("Probolinggo"),
    PURBALINGGA("Purbalingga"),
    PURWAKARTA("Purwakarta"),
    PURWOKERTO("Purwokerto"),
    PURWOREJO("Purworejo"),
    RABA("Raba"),
    RANGKAS_BITUNG("Rangkas Bitung"),
    RANTAU("Rantau"),
    RAYA("Raya"),
    REMBANG("Rembang"),
    RENGAT("Rengat"),
    RIAU("Riau"),
    ROTE_NDAO("Rote Ndao"),
    RUJAK("Rujak"),
    SABANG("Sabang"),
    SAGULING("Saguling"),
    SAMARINDA("Samarinda"),
    SAMPANG("Sampang"),
    SANGATTA("Sangatta"),
    SAWAHLUNTO("Sawahlunto"),
    SEKADAU("Sekadau"),
    SELONG("Selong"),
    SEMARANG("Semarang"),
    SERANG("Serang"),
    SERUI("Serui"),
    SIDOARJO("Sidoarjo"),
    SIGI_BIAK("Sigi Biak"),
    SIKKA("Sikka"),
    SINGAPARNA("Singaparna"),
    SINGARAJA("Singaraja"),
    SINGKAWANG("Singkawang"),
    SINJAI("Sinjai"),
    SITUBONDO("Situbondo"),
    SOLOK("Solok"),
    SOPPENG("Soppeng"),
    SORONG("Sorong"),
    SOUKI("Souki"),
    SRAGEN("Sragen"),
    SUBANG("Subang"),
    SUKABUMI("Sukabumi"),
    SUMBA("Sumba"),
    SUMBAWA("Sumbawa"),
    SUMEDANG("Sumedang"),
    SUMENEP("Sumenep"),
    SUMSEL("Sumsel"),
    SUMSEL_TENGAH("Sumsel Tengah"),
    SUMSEL_TIMUR("Sumsel Timur"),
    SUNGAI_PENUH("Sungai Penuh"),
    SURABAYA("Surabaya"),
    TABANAN("Tabanan"),
    TAHUNA("Tahuna"),
    TAKALAR("Takalar"),
    TANGERANG("Tangerang"),
    TANJUNG("Tanjung"),
    TANJUNG_BALAI("Tanjung Balai"),
    TANJUNG_ENIM("Tanjung Enim"),
    TANJUNG_PINANG("Tanjung Pinang"),
    TAPANULI("Tapanuli"),
    TARAKAN("Tarakan"),
    TASIKMALAYA("Tasikmalaya"),
    TEBING_TINGGI("Tebing Tinggi"),
    TEGAL("Tegal"),
    TELUK_KUANTAN("Teluk Kuantan"),
    TELUK_WONDAMA("Teluk Wondama"),
    TEMANGGUNG("Temanggung"),
    TERNATE("Ternate"),
    TOBELO("Tobelo"),
    TOJO_UNA_UNA("Tojo Una-Una"),
    TOLI_TOLI("Toli-Toli"),
    TOMOHON("Tomohon"),
    TONDANO("Tondano"),
    TUBAN("Tuban"),
    TUAL("Tual"),
    TULANG_BAWANG("Tulang Bawang"),
    TULUNGAGUNG("Tulungagung"),
    WAJO("Wajo"),
    WATAMPONE("Watampone"),
    WATES("Wates"),
    WONOGIRI("Wonogiri"),
    WONOSOBO("Wonosobo"),
    YOGYAKARTA("Yogyakarta");

    private String description;

    Kota(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
